library(shiny)
library(leaflet)
library(tidyverse)
library(rgdal)

totalData <- read_csv("United_States_COVID-19_Cases_and_Deaths_by_State_over_Time.csv")
totalData$detection_date <- as.Date(totalData$submission_date, format = "%m/%d/%Y")
states <- read_csv("states")
colnames(states) <- c("StateName", "Abbreviation")
totalData <- left_join(totalData, states, by = c("state" = "Abbreviation"))
